Add a vtk reader tailored for Shamrock dumps.
ttricco/sarracen pull request #84
Opened 2024-07-09 01:46 UTC by y-lapeyre

Shamrock is a new GPU hydrodynamics/magnetohydrodynamics code for astrophysical simulations. It was presented at the 5th Phantom Workshop and will be made public later this year.

2024-07-10 01:01 UTC, ttricco requested changes
1. read_header() and read_vtk_series() are not used. I recommend removing this code, or do you plan to make use of this in future versions of Shamrock?

2. My inclination would be to rename this to read_shamrock(), as I would expect read_vtk() to be a general function to handle any .vtk file (which is not the case).

3. Does the .vtk file not contain the pmass value? It would be better to not have pmass as a function argument if it can be read from the file.

2024-07-11 15:30 UTC, ttricco requested changes

2024-07-11 15:30 UTC, ttricco commented on sarracen/readers/read_shamrock.py
> +    df['Bz'] = df['B/rhoz'] * df['rho']
Sorry just another comment I should have realized before now -- what if the file doesn't contain magnetic field? I can imagine that you would often pure hydro calculations.

A simple check would be:
`if 'B/rhox' in df.columns:`
`    df['Bx'] = df['B/rhox'] * df['rho']`

2024-07-17 00:10 UTC, ttricco commented
I have renamed read_vtk() to read_shamrock() and will merge this in. Thanks for your contribution. Please raise an issue or open a new PR if any changes are needed.

2024-07-17 00:10 UTC, merged

2024-07-21 23:05 UTC, y-lapeyre commented
Sorry for my late response, was out of internet for a week. Thank you very much! And unfortunately the VTK format doesn't allow for much metadata to be stored. According to the creators of the format, if one wants to store constants in the header, they should use an extra column for it... which is not ideal. We will come up with a Shamrock native format in the future.